# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_movie_widget(object):
    def setupUi(self, movie_widget):
        movie_widget.setObjectName("movie_widget")
        movie_widget.resize(615, 787)
        self.gridLayout_4 = QtWidgets.QGridLayout(movie_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.movie_widget_vl = QtWidgets.QVBoxLayout()
        self.movie_widget_vl.setObjectName("movie_widget_vl")
        self.movie_select_gb = QtWidgets.QGroupBox(movie_widget)
        self.movie_select_gb.setCheckable(True)
        self.movie_select_gb.setObjectName("movie_select_gb")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.movie_select_gb)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.movie_select_gb)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_5.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.movie_select_gb)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_5.addWidget(self.lineEdit_7, 1, 2, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.movie_select_gb)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_5.addWidget(self.spinBox_3, 1, 3, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.movie_select_gb)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_5.addWidget(self.spinBox_4, 1, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.movie_select_gb)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.movie_select_gb)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.movie_select_gb)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.movie_select_gb)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.movie_select_gb)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.movie_select_gb)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 4, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.movie_select_gb)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 0, 5, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.movie_select_gb)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.movie_widget_vl.addWidget(self.movie_select_gb)
        self.movie_canvas_hl = QtWidgets.QHBoxLayout()
        self.movie_canvas_hl.setObjectName("movie_canvas_hl")
        self.widget = QtWidgets.QWidget(movie_widget)
        self.widget.setMinimumSize(QtCore.QSize(200, 400))
        self.widget.setObjectName("widget")
        self.movie_canvas_hl.addWidget(self.widget)
        self.verticalSlider = QtWidgets.QSlider(movie_widget)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.movie_canvas_hl.addWidget(self.verticalSlider)
        self.movie_widget_vl.addLayout(self.movie_canvas_hl)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(movie_widget)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 1, 5, 1, 1)
        self.sb_frameno = QtWidgets.QSpinBox(movie_widget)
        self.sb_frameno.setObjectName("sb_frameno")
        self.gridLayout.addWidget(self.sb_frameno, 1, 7, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(movie_widget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 9, 1, 1)
        self.btn_prev = QtWidgets.QPushButton(movie_widget)
        self.btn_prev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../repos/elzar/icons/appbar.navigate.previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon)
        self.btn_prev.setObjectName("btn_prev")
        self.gridLayout.addWidget(self.btn_prev, 1, 2, 1, 1)
        self.btn_play = QtWidgets.QPushButton(movie_widget)
        self.btn_play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../repos/elzar/icons/appbar.control.play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon1)
        self.btn_play.setCheckable(False)
        self.btn_play.setObjectName("btn_play")
        self.gridLayout.addWidget(self.btn_play, 1, 1, 1, 1)
        self.btn_next = QtWidgets.QPushButton(movie_widget)
        self.btn_next.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../repos/elzar/icons/appbar.navigate.next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon2)
        self.btn_next.setObjectName("btn_next")
        self.gridLayout.addWidget(self.btn_next, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(movie_widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(movie_widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(movie_widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 8, 1, 1)
        self.frame_slider = QtWidgets.QSlider(movie_widget)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.gridLayout.addWidget(self.frame_slider, 0, 1, 1, 9)
        self.movie_widget_vl.addLayout(self.gridLayout)
        self.pushButton = QtWidgets.QPushButton(movie_widget)
        self.pushButton.setObjectName("pushButton")
        self.movie_widget_vl.addWidget(self.pushButton)
        self.frame_enhancements = QtWidgets.QFrame(movie_widget)
        self.frame_enhancements.setMinimumSize(QtCore.QSize(0, 140))
        self.frame_enhancements.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_enhancements.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_enhancements.setObjectName("frame_enhancements")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_enhancements)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 591, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_enhancements = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.gb_enhancements.setMinimumSize(QtCore.QSize(0, 100))
        self.gb_enhancements.setCheckable(True)
        self.gb_enhancements.setObjectName("gb_enhancements")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gb_enhancements)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.bg_sub_hl_8 = QtWidgets.QHBoxLayout()
        self.bg_sub_hl_8.setObjectName("bg_sub_hl_8")
        self.bgsub_cb_6 = QtWidgets.QCheckBox(self.gb_enhancements)
        self.bgsub_cb_6.setObjectName("bgsub_cb_6")
        self.bg_sub_hl_8.addWidget(self.bgsub_cb_6)
        self.bgsub_tb_6 = QtWidgets.QToolButton(self.gb_enhancements)
        self.bgsub_tb_6.setObjectName("bgsub_tb_6")
        self.bg_sub_hl_8.addWidget(self.bgsub_tb_6)
        self.gridLayout_8.addLayout(self.bg_sub_hl_8, 3, 1, 1, 1)
        self.gl_enhancements_3 = QtWidgets.QGridLayout()
        self.gl_enhancements_3.setObjectName("gl_enhancements_3")
        self.fg_extract_hl_5 = QtWidgets.QHBoxLayout()
        self.fg_extract_hl_5.setObjectName("fg_extract_hl_5")
        self.fg_extract_cb_5 = QtWidgets.QCheckBox(self.gb_enhancements)
        self.fg_extract_cb_5.setObjectName("fg_extract_cb_5")
        self.fg_extract_hl_5.addWidget(self.fg_extract_cb_5)
        self.fg_extract_tb_5 = QtWidgets.QToolButton(self.gb_enhancements)
        self.fg_extract_tb_5.setObjectName("fg_extract_tb_5")
        self.fg_extract_hl_5.addWidget(self.fg_extract_tb_5)
        self.gl_enhancements_3.addLayout(self.fg_extract_hl_5, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gl_enhancements_3, 2, 0, 1, 1)
        self.bg_sub_hl_9 = QtWidgets.QHBoxLayout()
        self.bg_sub_hl_9.setObjectName("bg_sub_hl_9")
        self.bgsub_cb_7 = QtWidgets.QCheckBox(self.gb_enhancements)
        self.bgsub_cb_7.setObjectName("bgsub_cb_7")
        self.bg_sub_hl_9.addWidget(self.bgsub_cb_7)
        self.bgsub_tb_7 = QtWidgets.QToolButton(self.gb_enhancements)
        self.bgsub_tb_7.setObjectName("bgsub_tb_7")
        self.bg_sub_hl_9.addWidget(self.bgsub_tb_7)
        self.gridLayout_8.addLayout(self.bg_sub_hl_9, 3, 0, 1, 1)
        self.enhancements_gl_4 = QtWidgets.QGridLayout()
        self.enhancements_gl_4.setObjectName("enhancements_gl_4")
        self.fg_extract_hl_6 = QtWidgets.QHBoxLayout()
        self.fg_extract_hl_6.setObjectName("fg_extract_hl_6")
        self.fg_extract_cb_6 = QtWidgets.QCheckBox(self.gb_enhancements)
        self.fg_extract_cb_6.setObjectName("fg_extract_cb_6")
        self.fg_extract_hl_6.addWidget(self.fg_extract_cb_6)
        self.fg_extract_tb_6 = QtWidgets.QToolButton(self.gb_enhancements)
        self.fg_extract_tb_6.setObjectName("fg_extract_tb_6")
        self.fg_extract_hl_6.addWidget(self.fg_extract_tb_6)
        self.enhancements_gl_4.addLayout(self.fg_extract_hl_6, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.enhancements_gl_4, 4, 0, 1, 1)
        self.bg_sub_hl_10 = QtWidgets.QHBoxLayout()
        self.bg_sub_hl_10.setObjectName("bg_sub_hl_10")
        self.bg_extract_cb_3 = QtWidgets.QCheckBox(self.gb_enhancements)
        self.bg_extract_cb_3.setObjectName("bg_extract_cb_3")
        self.bg_sub_hl_10.addWidget(self.bg_extract_cb_3)
        self.bg_extract_tb_3 = QtWidgets.QToolButton(self.gb_enhancements)
        self.bg_extract_tb_3.setObjectName("bg_extract_tb_3")
        self.bg_sub_hl_10.addWidget(self.bg_extract_tb_3)
        self.gridLayout_8.addLayout(self.bg_sub_hl_10, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.gb_enhancements)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.gb_enhancements)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.gb_enhancements)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_8.addWidget(self.line, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.gb_enhancements)
        self.movie_widget_vl.addWidget(self.frame_enhancements)
        self.gridLayout_4.addLayout(self.movie_widget_vl, 0, 0, 1, 1)

        self.retranslateUi(movie_widget)
        QtCore.QMetaObject.connectSlotsByName(movie_widget)

    def retranslateUi(self, movie_widget):
        _translate = QtCore.QCoreApplication.translate
        movie_widget.setWindowTitle(_translate("movie_widget", "Form"))
        self.movie_select_gb.setTitle(_translate("movie_widget", "Movie file"))
        self.pushButton_3.setText(_translate("movie_widget", "Load frames"))
        self.label_7.setText(_translate("movie_widget", "Machine"))
        self.label_8.setText(_translate("movie_widget", "Camera"))
        self.label_9.setText(_translate("movie_widget", "Pulse"))
        self.label_10.setText(_translate("movie_widget", "Start frame"))
        self.label_11.setText(_translate("movie_widget", "End frame"))
        self.pushButton_5.setText(_translate("movie_widget", "Load meta"))
        self.label_3.setText(_translate("movie_widget", "Speed"))
        self.label.setText(_translate("movie_widget", "Frame"))
        self.label_2.setText(_translate("movie_widget", "Time"))
        self.pushButton.setText(_translate("movie_widget", "PushButton"))
        self.gb_enhancements.setTitle(_translate("movie_widget", "Image enhancements:"))
        self.bgsub_cb_6.setText(_translate("movie_widget", "Gamma enhance"))
        self.bgsub_tb_6.setText(_translate("movie_widget", "..."))
        self.fg_extract_cb_5.setText(_translate("movie_widget", "Extract foreground"))
        self.fg_extract_tb_5.setText(_translate("movie_widget", "..."))
        self.bgsub_cb_7.setText(_translate("movie_widget", "Reduce noise"))
        self.bgsub_tb_7.setText(_translate("movie_widget", "..."))
        self.fg_extract_cb_6.setText(_translate("movie_widget", "Sharpen"))
        self.fg_extract_tb_6.setText(_translate("movie_widget", "..."))
        self.bg_extract_cb_3.setText(_translate("movie_widget", "Extract background"))
        self.bg_extract_tb_3.setText(_translate("movie_widget", "..."))
        self.checkBox.setText(_translate("movie_widget", "Apply enhancements"))
        self.pushButton_2.setText(_translate("movie_widget", "Apply to all frames"))

